### ISSUE TITLE
Add html.json for support snippets for HTML files, currently only works in XML files

### ISSUE THREAD

**Issue by darkyelox** [tsvetan-ganev/nativescript-vscode-snippets#12]
The snippets in this project are only available for XML files but Nativescript supports HTML extension in their templates.

**Comment by smellyboxers** [comment]
yes please! It bothers me that I can't get support for NativeScript elements in Angular NativeScript -.-

**Comment by atmosuwiryo** [comment]
Workaround:
1. Go to extensions folder here:

> Windows: %USERPROFILE%\.vscode\extensions
macOS/Linux: $HOME/.vscode/extensions

2. Go to this extensions folder:

> tsvetan-ganev.nativescript-xml-snippets-1.0.6

3. Open package.json and change this line:

>  "language": "xml",

to 

>  "language": "html",

That's it.

**Comment by tsvetan-ganev** [comment]
Sorry for the late reply. HTML is now added to the list of supported languages.
